# backend/harness/generate_ieee_minipaper.py
# (NEW: Generate a minimal, compilable IEEEtran LaTeX paper skeleton that includes the generated Results section.)
#
# Inputs (under --results-dir):
#   - latex/ieee_results_section_en.tex (generated by generate_ieee_results_section.py)
#   - latex/ieee_results_section_fr.tex (optional)
#
# Outputs:
#   - <results-dir>/latex/ieee_minipaper_en.tex
#   - <results-dir>/latex/ieee_minipaper_fr.tex
#   - <results-dir>/latex/README_COMPILE.txt
#
# Usage:
#   python backend/harness/generate_ieee_minipaper.py --results-dir results_1000
#
from __future__ import annotations

import argparse
import os


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def read_text(path: str) -> str:
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write_text(path: str, content: str) -> None:
    ensure_dir(os.path.dirname(path) or ".")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.rstrip() + "\n")
    print(f"[MCAD/MINIPAPER] {path}")


def make_minipaper(lang: str, class_opt: str, results_filename: str) -> str:
    title = "MCAD: Contextual Mask for Objective-Aware Decision Analysis (Prototype Report)"
    if lang == "fr":
        title = "MCAD : Masque contextuel pour l'analyse décisionnelle centrée objectif (Rapport prototype)"

    # IEEEtran minimal skeleton (conference by default). User can switch to journal.
    tex = r"""\documentclass[%s]{IEEEtran}

\usepackage{graphicx}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{url}

\title{%s}

\author{
\IEEEauthorblockN{Author Name}
\IEEEauthorblockA{Affiliation\\
Email}
}

\begin{document}
\maketitle

\begin{abstract}
%s
\end{abstract}

\begin{IEEEkeywords}
Context-aware OLAP, contextual knowledge graph, objective-centric analytics, explainability, MCAD.
\end{IEEEkeywords}

\section{Introduction}
%s

\section{Background and MCAD Model}
%s

\section{Implementation}
%s

\input{%s}

\section{Threats to Validity}
%s

\section{Conclusion}
%s

\bibliographystyle{IEEEtran}
\bibliography{references}

\end{document}
""" % (
        class_opt,
        title,
        "TODO: concise abstract (5--7 lines) summarizing MCAD and the CKG-first validation.",
        "TODO: motivation, problem statement, contributions, and paper organization.",
        "TODO: CKG + MCAD formalization (SAT/Real/Ceval/φ) and relation to strategic objectives.",
        "TODO: prototype architecture, datasets (FoodMart/other), scenarios, and evaluation pipeline.",
        results_filename.replace("\\", "/"),
        "TODO: discuss dataset representativeness, parameter sensitivity, and construct validity of metrics.",
        "TODO: summarize findings and outline future work.",
    )
    return tex


def compile_readme() -> str:
    return (
        "=== Compile instructions (IEEEtran) ===\n"
        "Assumption: you are in <results-dir>/latex/\n\n"
        "1) If you have BibTeX references:\n"
        "   pdflatex ieee_minipaper_en.tex\n"
        "   bibtex ieee_minipaper_en\n"
        "   pdflatex ieee_minipaper_en.tex\n"
        "   pdflatex ieee_minipaper_en.tex\n\n"
        "2) If you do NOT use bibliography yet, comment out the bibliography lines:\n"
        "   %\\bibliographystyle{IEEEtran}\n"
        "   %\\bibliography{references}\n\n"
        "Notes:\n"
        "- Figures are referenced relatively from the latex/ folder (../figures/...).\n"
        "- Tables are included with \\input{../tables/...}.\n"
        "- Switch to journal style by changing the documentclass option, e.g. [journal].\n"
    )


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate a minimal IEEEtran LaTeX paper skeleton that includes MCAD results section.")
    p.add_argument("--results-dir", type=str, default="results")
    p.add_argument("--class-opt", type=str, default="conference", help="IEEEtran class option: conference (default) or journal")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    results_dir = args.results_dir
    latex_dir = os.path.join(results_dir, "latex")
    ensure_dir(latex_dir)

    # We reference the generated results section by filename (same folder)
    en_results = os.path.join(latex_dir, "ieee_results_section_en.tex")
    fr_results = os.path.join(latex_dir, "ieee_results_section_fr.tex")

    if not os.path.exists(en_results):
        raise FileNotFoundError(f"Missing {en_results}. Run generate_ieee_results_section.py first.")

    en_tex = make_minipaper(lang="en", class_opt=args.class_opt, results_filename="ieee_results_section_en.tex")
    write_text(os.path.join(latex_dir, "ieee_minipaper_en.tex"), en_tex)

    # FR version only if the FR results section exists
    if os.path.exists(fr_results):
        fr_tex = make_minipaper(lang="fr", class_opt=args.class_opt, results_filename="ieee_results_section_fr.tex")
        write_text(os.path.join(latex_dir, "ieee_minipaper_fr.tex"), fr_tex)

    write_text(os.path.join(latex_dir, "README_COMPILE.txt"), compile_readme())

    print("[MCAD/MINIPAPER] Done.")


if __name__ == "__main__":
    main()
